const PRODUCTS = [
    {
        id: 1,
        name: 'The Spike',
        subtitle: "Men's Linen Aloha Shirt",
        price: 98,
        image: 'product-1.png',
        bg: 'linear-gradient(135deg, #F0D5A8 0%, #E8B280 100%)',
        category: 'Apparel',
        sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
        description: 'Hand-printed with our signature hedgehog hibiscus motif, The Spike is what happens when island living meets the world\'s most endearing animal. 100% linen, slightly oversized, extremely unapologetic.',
        badge: null,
    },
    {
        id: 2,
        name: 'Quillow',
        subtitle: 'Beach Tote Bag',
        price: 64,
        image: 'product-2.png',
        bg: 'linear-gradient(135deg, #F5C6A0 0%, #E8A070 100%)',
        category: 'Accessories',
        sizes: null,
        description: 'Big enough for a beach day, tough enough for a hedgehog-load of stuff. Heavyweight canvas with embroidered hedgehog detail and interior zip pocket. Comes in natural and midnight.',
        badge: null,
    },
    {
        id: 3,
        name: 'Prickle Shades',
        subtitle: 'Polarized Sunglasses',
        price: 79,
        image: 'product-3.png',
        bg: 'linear-gradient(135deg, #A8D0E8 0%, #70B0D0 100%)',
        category: 'Accessories',
        sizes: null,
        description: 'Tortoiseshell frames inspired by the warm hues of a hedgehog\'s quills. UV400 polarized lenses. A hedgehog needs to look good in the sun, and so do you.',
        badge: null,
    },
    {
        id: 4,
        name: 'Hogana Slide',
        subtitle: 'Leather Sandals',
        price: 112,
        image: 'product-4.png',
        bg: 'linear-gradient(135deg, #D8C8A8 0%, #C0A880 100%)',
        category: 'Footwear',
        sizes: ['US 6', 'US 7', 'US 8', 'US 9', 'US 10', 'US 11', 'US 12'],
        description: 'Built for the hedgehog who never rushes. Full-grain leather footbed, cushioned sole, adjustable strap. Looks good on a deck, looks better on a beach.',
        badge: null,
    },
    {
        id: 5,
        name: "Spike's Hawaiian",
        subtitle: 'Art Print',
        price: 45,
        image: 'product-5.png',
        bg: 'linear-gradient(135deg, #FDE8A0 0%, #F8C860 100%)',
        category: 'Art',
        sizes: null,
        description: 'Our most requested print. Spike, rendered in watercolor glory, absolutely destroying a pineapple pizza with zero regrets. 8×10 archival print, unframed. Hang it in your kitchen. Frame it. Never apologize for it.',
        badge: 'Fan Favourite',
    },
    {
        id: 6,
        name: 'The Quill Cap',
        subtitle: 'Woven Sun Hat',
        price: 58,
        image: 'product-6.png',
        bg: 'linear-gradient(135deg, #E8D5A0 0%, #D0B870 100%)',
        category: 'Accessories',
        sizes: ['S/M', 'L/XL'],
        description: 'A proper sun hat for the discerning hedgehog enthusiast. Wide brim, woven from natural fibers, with our hedgehog motif woven into the hatband. Packable. Essential.',
        badge: null,
    },
];
